/**
 * 99 Esmaül Hüsna - Allah'ın Güzel İsimleri
 */

export interface EsmaItem {
    id: number;
    arapca: string;
    okunusu: string;
    anlami: string;
}

export const ESMAUL_HUSNA: EsmaItem[] = [
    { id: 1, arapca: 'الله', okunusu: 'Allah', anlami: 'Tek ve gerçek ilah' },
    { id: 2, arapca: 'الرَّحْمَنُ', okunusu: 'Er-Rahman', anlami: 'Dünyada herkese merhamet eden' },
    { id: 3, arapca: 'الرَّحِيمُ', okunusu: 'Er-Rahim', anlami: 'Ahirette müminlere merhamet eden' },
    { id: 4, arapca: 'الْمَلِكُ', okunusu: 'El-Melik', anlami: 'Mülkün gerçek sahibi' },
    { id: 5, arapca: 'الْقُدُّوسُ', okunusu: 'El-Kuddüs', anlami: 'Her türlü eksiklikten münezzeh' },
    { id: 6, arapca: 'السَّلَامُ', okunusu: 'Es-Selam', anlami: 'Selamet veren, esenlik kaynağı' },
    { id: 7, arapca: 'الْمُؤْمِنُ', okunusu: 'El-Mü\'min', anlami: 'Güven veren, iman nurunu veren' },
    { id: 8, arapca: 'الْمُهَيْمِنُ', okunusu: 'El-Müheymin', anlami: 'Her şeyi gözetip koruyan' },
    { id: 9, arapca: 'الْعَزِيزُ', okunusu: 'El-Aziz', anlami: 'Yenilmez, mutlak güç sahibi' },
    { id: 10, arapca: 'الْجَبَّارُ', okunusu: 'El-Cebbar', anlami: 'İradesini her zaman yürüten' },
    { id: 11, arapca: 'الْمُتَكَبِّرُ', okunusu: 'El-Mütekebbir', anlami: 'Büyüklükte eşi olmayan' },
    { id: 12, arapca: 'الْخَالِقُ', okunusu: 'El-Halik', anlami: 'Her şeyi yaratan' },
    { id: 13, arapca: 'الْبَارِئُ', okunusu: 'El-Bari', anlami: 'Her şeyi uyumlu yaratan' },
    { id: 14, arapca: 'الْمُصَوِّرُ', okunusu: 'El-Musavvir', anlami: 'Her şeye şekil veren' },
    { id: 15, arapca: 'الْغَفَّارُ', okunusu: 'El-Gaffar', anlami: 'Günahları affeden' },
    { id: 16, arapca: 'الْقَهَّارُ', okunusu: 'El-Kahhar', anlami: 'Her şeye galip gelen' },
    { id: 17, arapca: 'الْوَهَّابُ', okunusu: 'El-Vehhab', anlami: 'Karşılıksız veren' },
    { id: 18, arapca: 'الرَّزَّاقُ', okunusu: 'Er-Rezzak', anlami: 'Bütün canlıları rızıklandıran' },
    { id: 19, arapca: 'الْفَتَّاحُ', okunusu: 'El-Fettah', anlami: 'Her türlü zorluğu açan' },
    { id: 20, arapca: 'اَلْعَلِيمُ', okunusu: 'El-Alim', anlami: 'Her şeyi bilen' },
    { id: 21, arapca: 'الْقَابِضُ', okunusu: 'El-Kabıd', anlami: 'Rızkı daraltan' },
    { id: 22, arapca: 'الْبَاسِطُ', okunusu: 'El-Basıt', anlami: 'Rızkı genişleten' },
    { id: 23, arapca: 'الْخَافِضُ', okunusu: 'El-Hafıd', anlami: 'Dereceleri alçaltan' },
    { id: 24, arapca: 'الرَّافِعُ', okunusu: 'Er-Rafi', anlami: 'Dereceleri yükselten' },
    { id: 25, arapca: 'الْمُعِزُّ', okunusu: 'El-Muizz', anlami: 'İzzet ve şeref veren' },
    { id: 26, arapca: 'المُذِلُّ', okunusu: 'El-Müzill', anlami: 'Zillete düşüren' },
    { id: 27, arapca: 'السَّمِيعُ', okunusu: 'Es-Semi', anlami: 'Her şeyi işiten' },
    { id: 28, arapca: 'الْبَصِيرُ', okunusu: 'El-Basir', anlami: 'Her şeyi gören' },
    { id: 29, arapca: 'الْحَكَمُ', okunusu: 'El-Hakem', anlami: 'Hükmeden, hakim' },
    { id: 30, arapca: 'الْعَدْلُ', okunusu: 'El-Adl', anlami: 'Mutlak adil' },
    { id: 31, arapca: 'اللَّطِيفُ', okunusu: 'El-Latif', anlami: 'En ince işlerin bile bilicisi' },
    { id: 32, arapca: 'الْخَبِيرُ', okunusu: 'El-Habir', anlami: 'Her şeyden haberdar' },
    { id: 33, arapca: 'الْحَلِيمُ', okunusu: 'El-Halim', anlami: 'Çok yumuşak davranan' },
    { id: 34, arapca: 'الْعَظِيمُ', okunusu: 'El-Azim', anlami: 'Büyüklükte sınırsız' },
    { id: 35, arapca: 'الْغَفُورُ', okunusu: 'El-Gafur', anlami: 'Çok bağışlayan' },
    { id: 36, arapca: 'الشَّكُورُ', okunusu: 'Eş-Şekur', anlami: 'Az iyiliğe çok karşılık veren' },
    { id: 37, arapca: 'الْعَلِيُّ', okunusu: 'El-Aliyy', anlami: 'Yücelikte sınırsız' },
    { id: 38, arapca: 'الْكَبِيرُ', okunusu: 'El-Kebir', anlami: 'Büyüklükte sonsuz' },
    { id: 39, arapca: 'الْحَفِيظُ', okunusu: 'El-Hafiz', anlami: 'Her şeyi koruyan' },
    { id: 40, arapca: 'المُقيِت', okunusu: 'El-Mukit', anlami: 'Rızık veren, gücü yeten' },
    { id: 41, arapca: 'الْحَسِيبُ', okunusu: 'El-Hasib', anlami: 'Hesaba çeken' },
    { id: 42, arapca: 'الْجَلِيلُ', okunusu: 'El-Celil', anlami: 'Celal ve azamet sahibi' },
    { id: 43, arapca: 'الْكَرِيمُ', okunusu: 'El-Kerim', anlami: 'Çok cömert' },
    { id: 44, arapca: 'الرَّقِيبُ', okunusu: 'Er-Rakib', anlami: 'Her şeyi gözetleyen' },
    { id: 45, arapca: 'الْمُجِيبُ', okunusu: 'El-Mücib', anlami: 'Dualara cevap veren' },
    { id: 46, arapca: 'الْوَاسِعُ', okunusu: 'El-Vasi', anlami: 'Rahmeti geniş olan' },
    { id: 47, arapca: 'الْحَكِيمُ', okunusu: 'El-Hakim', anlami: 'Her işi hikmetli' },
    { id: 48, arapca: 'الْوَدُودُ', okunusu: 'El-Vedud', anlami: 'Çok seven ve sevilen' },
    { id: 49, arapca: 'الْمَجِيدُ', okunusu: 'El-Mecid', anlami: 'Şanı yüce' },
    { id: 50, arapca: 'الْبَاعِثُ', okunusu: 'El-Bais', anlami: 'Ölüleri dirilten' },
    { id: 51, arapca: 'الشَّهِيدُ', okunusu: 'Eş-Şehid', anlami: 'Her şeye şahit' },
    { id: 52, arapca: 'الْحَقُّ', okunusu: 'El-Hakk', anlami: 'Varlığı gerçek olan' },
    { id: 53, arapca: 'الْوَكِيلُ', okunusu: 'El-Vekil', anlami: 'Güvenilen vekil' },
    { id: 54, arapca: 'الْقَوِيُّ', okunusu: 'El-Kaviyy', anlami: 'Güçlü' },
    { id: 55, arapca: 'الْمَتِينُ', okunusu: 'El-Metin', anlami: 'Sağlam, güçlü' },
    { id: 56, arapca: 'الْوَلِيُّ', okunusu: 'El-Veliyy', anlami: 'Dost, yardımcı' },
    { id: 57, arapca: 'الْحَمِيدُ', okunusu: 'El-Hamid', anlami: 'Övülmeye layık' },
    { id: 58, arapca: 'الْمُحْصِي', okunusu: 'El-Muhsi', anlami: 'Her şeyi sayan' },
    { id: 59, arapca: 'الْمُبْدِئُ', okunusu: 'El-Mübdi', anlami: 'Yoktan var eden' },
    { id: 60, arapca: 'الْمُعِيدُ', okunusu: 'El-Muid', anlami: 'Yeniden yaratan' },
    { id: 61, arapca: 'الْمُحْيِي', okunusu: 'El-Muhyi', anlami: 'Hayat veren' },
    { id: 62, arapca: 'اَلْمُمِيتُ', okunusu: 'El-Mümit', anlami: 'Öldüren' },
    { id: 63, arapca: 'الْحَيُّ', okunusu: 'El-Hayy', anlami: 'Diri, ölümsüz' },
    { id: 64, arapca: 'الْقَيُّومُ', okunusu: 'El-Kayyum', anlami: 'Her şeyi ayakta tutan' },
    { id: 65, arapca: 'الْوَاجِدُ', okunusu: 'El-Vacid', anlami: 'Zengin, bulan' },
    { id: 66, arapca: 'الْمَاجِدُ', okunusu: 'El-Macid', anlami: 'Şerefli, yüce' },
    { id: 67, arapca: 'الْواحِدُ', okunusu: 'El-Vahid', anlami: 'Tek olan' },
    { id: 68, arapca: 'اَلصَّمَدُ', okunusu: 'Es-Samed', anlami: 'Hiçbir şeye muhtaç olmayan' },
    { id: 69, arapca: 'الْقَادِرُ', okunusu: 'El-Kadir', anlami: 'Her şeye gücü yeten' },
    { id: 70, arapca: 'الْمُقْتَدِرُ', okunusu: 'El-Muktedir', anlami: 'Kudret sahibi' },
    { id: 71, arapca: 'الْمُقَدِّمُ', okunusu: 'El-Mukaddim', anlami: 'Öne geçiren' },
    { id: 72, arapca: 'الْمُؤَخِّرُ', okunusu: 'El-Muahhir', anlami: 'Geri bırakan' },
    { id: 73, arapca: 'الأَوَّلُ', okunusu: 'El-Evvel', anlami: 'İlk, başlangıcı olmayan' },
    { id: 74, arapca: 'الآخِرُ', okunusu: 'El-Ahir', anlami: 'Son, sonu olmayan' },
    { id: 75, arapca: 'الظَّاهِرُ', okunusu: 'Ez-Zahir', anlami: 'Varlığı aşikar' },
    { id: 76, arapca: 'الْبَاطِنُ', okunusu: 'El-Batın', anlami: 'Gizli olan' },
    { id: 77, arapca: 'الْوَالِي', okunusu: 'El-Vali', anlami: 'Her şeyi idare eden' },
    { id: 78, arapca: 'الْمُتَعَالِي', okunusu: 'El-Müteali', anlami: 'Yücelikte üstün' },
    { id: 79, arapca: 'الْبَرُّ', okunusu: 'El-Berr', anlami: 'İyiliği çok olan' },
    { id: 80, arapca: 'التَّوَّابُ', okunusu: 'Et-Tevvab', anlami: 'Tövbeleri kabul eden' },
    { id: 81, arapca: 'الْمُنْتَقِمُ', okunusu: 'El-Müntekim', anlami: 'İntikam alan' },
    { id: 82, arapca: 'العَفُوُّ', okunusu: 'El-Afüvv', anlami: 'Affı çok olan' },
    { id: 83, arapca: 'الرَّؤُوفُ', okunusu: 'Er-Rauf', anlami: 'Çok şefkatli' },
    { id: 84, arapca: 'مَالِكُ الْمُلْكِ', okunusu: 'Malik-ül Mülk', anlami: 'Mülkün sahibi' },
    { id: 85, arapca: 'ذُوالْجَلَالِ وَالْإِكْرَامِ', okunusu: 'Zül-Celali vel-İkram', anlami: 'Celal ve ikram sahibi' },
    { id: 86, arapca: 'الْمُقْسِطُ', okunusu: 'El-Muksit', anlami: 'Adaletli' },
    { id: 87, arapca: 'الْجَامِعُ', okunusu: 'El-Cami', anlami: 'Toplayan' },
    { id: 88, arapca: 'الْغَنِيُّ', okunusu: 'El-Ganiyy', anlami: 'Zengin, muhtaç olmayan' },
    { id: 89, arapca: 'الْمُغْنِي', okunusu: 'El-Muğni', anlami: 'Zengin eden' },
    { id: 90, arapca: 'اَلْمَانِعُ', okunusu: 'El-Mani', anlami: 'Engelleyen' },
    { id: 91, arapca: 'الضَّارَّ', okunusu: 'Ed-Darr', anlami: 'Zarar veren' },
    { id: 92, arapca: 'النَّافِعُ', okunusu: 'En-Nafi', anlami: 'Fayda veren' },
    { id: 93, arapca: 'النُّورُ', okunusu: 'En-Nur', anlami: 'Nur, aydınlatan' },
    { id: 94, arapca: 'الْهَادِي', okunusu: 'El-Hadi', anlami: 'Hidayet veren' },
    { id: 95, arapca: 'الْبَدِيعُ', okunusu: 'El-Bedi', anlami: 'Eşsiz yaratan' },
    { id: 96, arapca: 'اَلْبَاقِي', okunusu: 'El-Baki', anlami: 'Varlığı sonsuz' },
    { id: 97, arapca: 'الْوَارِثُ', okunusu: 'El-Varis', anlami: 'Her şeyin varisi' },
    { id: 98, arapca: 'الرَّشِيدُ', okunusu: 'Er-Reşid', anlami: 'Doğru yolu gösteren' },
    { id: 99, arapca: 'الصَّبُورُ', okunusu: 'Es-Sabur', anlami: 'Çok sabırlı' },
];
