/**
 * 30 Günlük Mood İçerikleri
 * Her ruh hali için 30 adet benzersiz Ayet ve Dua içeriği.
 */

export interface MoodContent {
    ayet: string;
    dua: string;
}

export const MOOD_HAVUZU: Record<string, MoodContent[]> = {
    peaceful: [
        { ayet: "“Bilesiniz ki, kalpler ancak Allah’ı anmakla huzur bulur.” (Ra’d, 28)", dua: "Allah’ım, gönlüme inşirah ver, işimi kolaylaştır." },
        { ayet: "“O, inananların yüreklerine huzur ve sükûnet indirendir.” (Fetih, 4)", dua: "Ya Rabbi, bahşettiğin bu huzuru daim eyle, kalbimi nurunla doldur." },
        { ayet: "“Onlara hiçbir korku yoktur, onlar mahzun da olmayacaklardır.” (Bakara, 62)", dua: "Allah’ım, dünyada ve ahirette emin kıldığın kullarından eyle." },
        { ayet: "“Selam olsun size, yaptıklarınızdan ötürü.” (Nahl, 32)", dua: "Allah’ım, ruhumu selamete erdir ve beni iyilerle beraber kıl." },
        { ayet: "“Allah kullarına çok şefkatlidir.” (Bakara, 207)", dua: "Ey Merhametlilerin En Merhametlisi, kalbimdeki sevgi ve huzuru artır." },
        { ayet: "“Rabbin seni terk etmedi ve sana darılmadı.” (Duha, 3)", dua: "Rabbim, senin varlığının huzuruyla her daim mutmain eyle." },
        { ayet: "“O, semâlardan ve yerden bir lütuftur.” (Lokman, 20)", dua: "Allah’ım, verdiğin nimetlerin şuurunda bir huzur ömrü nasip et." },
        { ayet: "“Sabrettiğiniz için size selam olsun!” (Ra’d, 24)", dua: "Ya Rabbi, sabrın sonundaki selameti ve sükuneti kalbime nakşet." },
        { ayet: "“Şüphesiz Rabbin, duayı iştirak edendir.” (İbrahim, 39)", dua: "Allah’ım, huzurlu anlarımda da sana şükretmeyi bana unutturma." },
        { ayet: "“Allah size bir genişlik ve ferahlık verecektir.” (Talak, 7)", dua: "Rabbim, ruhumdaki bu genişliği ebedi saadetin öncüsü eyle." },
        // 11-30 arasını çeşitlendirerek devam ettiriyoruz...
        { ayet: "“Göklerin ve yerin mülkü Allah’ındır.” (Nur, 42)", dua: "Sahibim sensin, senin mülkünde seninle olmanın huzuru bana yeter." },
        { ayet: "“O, size her istediğiniz şeyi verdi.” (İbrahim, 34)", dua: "Yüce Rabbim, huzurumu ihsanınla bereketlendir." },
        { ayet: "“İyilik edenlere karşılığı ancak iyiliktir.” (Rahman, 60)", dua: "Allah’ım, kalbimdeki iyilikleri huzuruma vesile kıl." },
        { ayet: "“Rabbiniz, size geniş bir merhamet sahibidir.” (En’am, 147)", dua: "Merhametinle kuşatılmış bir kalp huzuru nasip et." },
        { ayet: "“Allah, dilediğine hesapsız rızık verir.” (Bakara, 212)", dua: "Rabbim, manevi rızkım olan huzuru kalbimden eksik etme." },
        { ayet: "“O, her şeyi bilen ve görendir.” (İsra, 30)", dua: "Görüldüğümü bilmenin huzuruyla yaşamayı nasip eyle." },
        { ayet: "“Şüphesiz Allah, tevbe edenleri sever.” (Bakara, 222)", dua: "Arınmış bir ruhun vereceği o eşsiz huzuru lütfeyle." },
        { ayet: "“Doğrusu biz sana apaçık bir fetih sağladık.” (Fetih, 1)", dua: "Gönlümün fethini ve sükunetini daim kıl Allah'ım." },
        { ayet: "“Allah sabredenlerle beraberdir.” (Bakara, 153)", dua: "Seninle olmanın eşsiz huzuruna beni erdir." },
        { ayet: "“Onlar korkusuzdurlar.” (Yunus, 62)", dua: "Korkularımı huzura tebdil eyle ya Rabbi." },
        { ayet: "“Rabbimiz Allah’tır diyenlere korku yoktur.” (Ahkaf, 13)", dua: "Sana olan imanımın huzurunu her nefesimde hissettir." },
        { ayet: "“Allah size kolaylık diler.” (Bakara, 185)", dua: "İşlerimi kolaylaştır, kalbimi ferahlat." },
        { ayet: "“Gönüller ancak O’nun zikriyle doyar.” (Ra’d, 28)", dua: "Zikrinle doyan, huzurla dolan bir kalp lütfet." },
        { ayet: "“Allah her şeye kadirdir.” (Mülk, 1)", dua: "Gücüne güvenmenin verdiği o büyük huzuru bana ver." },
        { ayet: "“O, sizinle beraberdir.” (Hadid, 4)", dua: "Issızlıkta ve kalabalıkta seninle olmanın huzuruyla yaşat." },
        { ayet: "“Rabbim lütufkardır.” (Yusuf, 100)", dua: "Lütfunla gelen bir huzur ömrü nasip eyle." },
        { ayet: "“Oruç tutmanız sizin için hayırlıdır.” (Bakara, 184)", dua: "İbadetlerimin verdiği o derin sükuneti daim kıl." },
        { ayet: "“O’nun lütfu çok büyüktür.” (Nisa, 113)", dua: "Büyük lütfunla kalbimi genişlet ve huzura ulaştır." },
        { ayet: "“Allah, güzel düşünenleri sever.” (Maide, 93)", dua: "Huzurlu ve güzel düşünceleri kalbime ilham et." },
        { ayet: "“Sonuç Allah’tan sakınanlarındır.” (A’raf, 128)", dua: "Yolun sonundaki o büyük huzura beni kavuştur." }
    ],
    sad: [
        { ayet: "“Gevşemeyin, hüzünlenmeyin; eğer inanmışsanız en üstün olan sizsiniz.” (Âl-i İmrân, 139)", dua: "Ya Rabbi, kederimi ve hüznümü sana arz ediyorum, bana ferahlık ver." },
        { ayet: "“Üzülme, şüphesiz Allah bizimle beraberdir.” (Tevbe, 40)", dua: "Yalnız kalmışlık hissinden ve kalbimi sıkan kederden sana sığındım." },
        { ayet: "“Elbette zorlukla beraber bir kolaylık vardır.” (İnşirah, 5)", dua: "Rabbim, yaşadığım bu zorluğun ardındaki o büyük kolaylığı bana göster." },
        { ayet: "“Doğrusu ben hüznümü ve kederimi Allah’a arz ederim.” (Yusuf, 86)", dua: "Ya Rabbi, gözyaşlarımı rahmetine vesile kıl, kalbimi onar." },
        { ayet: "“Rabbin seni terk etmedi.” (Duha, 3)", dua: "Kimsem kalmadığını hissettiğimde bile seninle olduğumu hatırlat." },
        { ayet: "“Allah, sabredenleri sever.” (Ali İmran, 146)", dua: "Bu hüzün günlerinde sabrımı artır, dayanak noktam sen ol." },
        { ayet: "“Sabret, senin sabrın ancak Allah’ın yardımıyladır.” (Nahl, 127)", dua: "Dermanı sende olan bu dertten beni selamete çıkar." },
        { ayet: "“Gönülleri ancak Allah’ın zikri doyurur.” (Ra’d, 28)", dua: "Hüzünlü kalbimi isminle tedavi eyle Allah'ım." },
        { ayet: "“Allah, sabredenle beraberdir.” (Bakara, 153)", dua: "Yanımda olduğunu hissettirerek kederimi dağıt." },
        { ayet: "“Rabbim! Göğsümü genişlet.” (Taha, 25)", dua: "Daralan ruhuma inşirah ver, hüzün perdesini arala." },
        { ayet: "“O, duaları iştirak edendir.” (İbrahim, 39)", dua: "Sessiz feryatlarımı duyup kalbime su serpen sensin." },
        { ayet: "“Allah hiçbir nefse gücünden fazlasını yüklemez.” (Bakara, 286)", dua: "Bu hüznün altında ezilmeme izin verme ya Rabbi." },
        { ayet: "“Sakın ümidinizi kesmeyin.” (Zümer, 53)", dua: "Ümit ışığımı söndürme, beni karanlıkta bırakma." },
        { ayet: "“O, geceyi ve gündüzü yaratandır.” (Enbiya, 33)", dua: "Bu karanlık gecenin sabahına beni selametle ulaştır." },
        { ayet: "“Allah tevbe edenleri sever.” (Bakara, 222)", dua: "Hatalarımın ağırlığından ve pişmanlık hüznünden beni kurtar." },
        { ayet: "“Rabbin her şeyi hakkıyla bilendir.” (Nisa, 26)", dua: "İçimdeki sızıyı bilen sensin, şifasını da sen ver." },
        { ayet: "“Sizin için hayır olanı Allah bilir.” (Bakara, 216)", dua: "Bu üzüntünün içinde gizli olan hayrı bana göster." },
        { ayet: "“O hayy ve kayyumdur.” (Bakara, 255)", dua: "Beni ayakta tutan ve hüzne galip getiren sensin." },
        { ayet: "“Sabır ve namazla yardım dileyin.” (Bakara, 45)", dua: "Namazımı ve sabrımı ruhuma ilaç eyle." },
        { ayet: "“Allah her şeye kafidir.” (Zümer, 36)", dua: "Hüznüme derman olarak senin varlığın bana yeter." },
        { ayet: "“Her güçlükten sonra bir ferahlık vardır.” (Talak, 7)", dua: "Ferahlık kapılarını benim için de aç Allah'ım." },
        { ayet: "“Allah’a güven, vekil olarak O yeter.” (Ahzab, 3)", dua: "Kederimi sana havale ettim, sen en güzel vekilsin." },
        { ayet: "“Seni yaratan Rabbinin adıyla oku!” (Alak, 1)", dua: "Hayatı ve acıyı senin adınla anlamlandırmamı nasip et." },
        { ayet: "“Onlar için bir korku yoktur.” (Bakara, 38)", dua: "Gelecek kaygısından ve geçmişin hüznünden beni emin kıl." },
        { ayet: "“Rabbin lütfu boldur.” (Ali İmran, 174)", dua: "Lütfunla bu hüzünlü kalbi sevindir ya Rabbi." },
        { ayet: "“İyilik edenlere Allah’ın rahmeti yakındır.” (A’raf, 56)", dua: "Rahmetinle bu kederli halimi değiştir." },
        { ayet: "“O, bağışlayan ve sevendir.” (Buruc, 14)", dua: "Sevginle kalbimdeki yaraları sar." },
        { ayet: "“Allah dilediğini hidayete erdirir.” (Bakara, 213)", dua: "Hüzünden çıkış yolunu bana göster." },
        { ayet: "“Allah’ın yardımı yakındır.” (Bakara, 214)", dua: "Çok geciktirmeden yardımıyla beni ferahlat ya Rabbi." },
        { ayet: "“Sonuç muttakilerindir.” (Hud, 49)", dua: "Bu imtihanın sonunda beni sevindir ve huzura erdir." }
    ],
    stressed: [
        { ayet: "“Allah, hiç kimseye gücünün üstünde bir şey yüklemez.” (Bakara, 286)", dua: "Allah’ım, sabrımı artır ve kalbime sükunet indir." },
        { ayet: "“Rabbimiz! Bize katından bir rahmet ver.” (Kehf, 10)", dua: "İşlerimin kördüğüm olduğu şu anlarda bana bir çıkış yolu lütfeyle." },
        { ayet: "“Kim Allah’a tevekkül ederse, O ona yeter.” (Talâk, 3)", dua: "Kaygılarımı ve yüklerimi sana bıraktım, sen benim yerime halleyle." },
        { ayet: "“Hüküm ancak Allah’ındır.” (Yusuf, 40)", dua: "Kontrol edemediğim her şeyin anahtarı sende, gönlümü ferah tut." },
        { ayet: "“O, her an bir yaratma halindedir.” (Rahman, 29)", dua: "Şu anki düğümümü hayra tebdil etmeye gücü yeten ancak sensin." },
        { ayet: "“Sizin için hayırlı olanı Allah bilir.” (Bakara, 216)", dua: "Zihnimi kurcalayan belirsizliklerde en hayırlı olanı kalbime ilham et." },
        { ayet: "“Sabredin, kuşkusuz Allah sabredenlerle beraberdir.” (Enfal, 46)", dua: "Aceleci ruhumu dindir, sükunetle beklemeyi nasip et." },
        { ayet: "“Göklerin ve yerin orduları Allah’ındır.” (Fetih, 4)", dua: "Zayıf kaldığımda senin sonsuz gücüne dayanmayı bana öğret." },
        { ayet: "“Darda kalana icabet eden O’dur.” (Neml, 62)", dua: "Sıkışmış hisseden kalbime genişlik ihsan eyle." },
        { ayet: "“O, her şeyi gözetleyendir.” (Nisa, 1)", dua: "Hiçbir çabamın boşa gitmediğini biliyorum, stresimi güvene çevir." },
        { ayet: "“Allah dilediğini ferahlatır.” (Kasas, 56)", dua: "Daralan ufkumu ve ruhumu genişliğe kavuştur." },
        { ayet: "“Rabbim şüphesiz her şeye şahittir.” (Buruc, 9)", dua: "Yorgunluğuma ve uykusuzluğuma şahit olan sensin, bana güç ver." },
        { ayet: "“Allah size bir kolaylık diler.” (Bakara, 185)", dua: "Üzerimdeki bu ağır yükü hafiflet ya Rabbi." },
        { ayet: "“O, her şeye güç yetirendir.” (Mülk, 1)", dua: "Yapamadıklarım için üzülmemeyi, gücüne sığınmayı nasip et." },
        { ayet: "“Allah, sabredenleri sever.” (Ali İmran, 146)", dua: "Stres anında dilimi ve kalbimi isyan etmekten koru." },
        { ayet: "“Rabbim her şeyi kuşatmıştır.” (Taha, 98)", dua: "Sorunlarım senin kudretinin yanında çok küçük, bunu bana hatırlat." },
        { ayet: "“Allah bir kapıyı kaparsa diğerini açar.” (Hadis meali)", dua: "Gördüğüm kapılar kapansa da sen hayırlı olanı açarsın, güveniyorum." },
        { ayet: "“Şüphesiz Rabbin her an gözetlemedediz.” (Fecr, 14)", dua: "Haksızlığa uğradığımda da, darda kaldığımda da seninle olduğumu bileyim." },
        { ayet: "“O, uykuyu dinlenme kıldı.” (Furkan, 47)", dua: "Zihnime ve bedenime şifa olacak bir sükunet ver." },
        { ayet: "“Allah yardımıyla kimi dilerse onu güçlendirir.” (Ali İmran, 13)", dua: "Beni dayanıklı kıl, baskı altında dahi takvamı korumamı sağla." },
        { ayet: "“Sabrederek yardım dileyin.” (Bakara, 153)", dua: "Stresimi duaya, kaygımı tevekküle dönüştür." },
        { ayet: "“O, her şeyi bilen ve görendir.” (İsra, 30)", dua: "Anlaşılamadığımı hissettiğimde beni en iyi bilen sensin." },
        { ayet: "“Semâ kapılarını bir su ile açtık.” (Kamer, 11)", dua: "Benim için de rahmet ve bereket kapılarını aç ya Rabbi." },
        { ayet: "“Gelecek günler geçmişten daha hayırlı olacaktır.” (Duha, 4)", dua: "Umutsuzluğa düştüğümde bu sözünle doğrulmamı sağla." },
        { ayet: "“Allah dilediğini bağışlar ve dilediğine azap eder.” (Maide, 18)", dua: "Senin adaletine ve merhametine teslim oldum." },
        { ayet: "“Rabbinin adını zikret.” (Müzzemmil, 8)", dua: "Zikrinle zihnimi boşaltmama ve sükunete ermeme yardım et." },
        { ayet: "“Niyetiniz halis ise Allah size yeter.” (Hadis)", dua: "Niyetimi düzelt, işlerimi temizle ve stresimi al." },
        { ayet: "“O, kalplerdekini hakkıyla bilendir.” (Teğabün, 4)", dua: "Kalbime esenlik ve dinginlik ver." },
        { ayet: "“Allah sizin dostunuzdur.” (Enfal, 40)", dua: "Dostun olan stresli bir kulunu yalnız bırakma." },
        { ayet: "“O, her şeye vekildir.” (Zümer, 62)", dua: "Vekilim sensin, işlerimin sonunu hayır eyle." }
    ],
    grateful: [
        { ayet: "“Eğer şükrederseniz, elbette size (nimetimi) artırırım.” (İbrâhim, 7)", dua: "Verdiğin nimetler için sana sonsuz şükürler olsun ya Rabbi." },
        { ayet: "“Allah’ın nimetini saymaya kalksanız, sayamazsınız.” (Nahl, 18)", dua: "Gördüğüm ve görmediğim her türlü nimetin için hamdolsun." },
        { ayet: "“Beni anın ki ben de sizi anayım, bana şükredin.” (Bakara, 152)", dua: "Anılmaya layık olan ancak sensin, kalbimi şükrünle canlı tut." },
        { ayet: "“Onlar için bitmez tükenmez mükafat vardır.” (İnşirah, 8)", dua: "Lütfundan gelen her şeye rıza gösterdim, şükrümü kabul et." },
        { ayet: "“Verdiğimiz helal rızıklardan yiyin ve şükredin.” (Bakara, 172)", dua: "Rızkımı helal ve bereketli eyle, şükrümü artır." },
        { ayet: "“Kim şükrederse ancak kendisi için şükretmiş olur.” (Lokman, 12)", dua: "Beni şükreden, nankörlükten uzak duran kullarından eyle." },
        { ayet: "“Şüphesiz Rabbin, insanlara karşı lütuf sahibidir.” (Neml, 73)", dua: "Lütfuna muhatap olmanın verdiği o asil mutlulukla şükrediyorum." },
        { ayet: "“Ve O, size her istediğiniz şeyi verdi.” (İbrahim, 34)", dua: "İstediklerimi ve istemeyi bilemediklerimi verdiğin için hamdolsun." },
        { ayet: "“De ki: Hamd Allah’a mahsustur.” (Neml, 93)", dua: "Her halim için elhamdülillah, her nefesim için şükürler olsun." },
        { ayet: "“O, rızık verenlerin en hayırlısıdır.” (Cuma, 11)", dua: "Ruhumu da bedenimi de en güzel şekilde besleyen sensin." },
        { ayet: "“Rabbinin nimetini minnetle an.” (Duha, 11)", dua: "Nezaketle verdiğin her ikramın için sana minnettarım." },
        { ayet: "“Kim iyilik yaparsa onun sevabını artırırız.” (Şura, 23)", dua: "İyilik yapabilme imkanı verdiğin için dahi sana şükürler olsun." },
        { ayet: "“Allah tevbe edenleri sever.” (Bakara, 222)", dua: "Tevbe edebilme ve sana yönelebilme nimetine şükürler olsun." },
        { ayet: "“Şüphesiz Allah, sabredenlerle beraberdir.” (Bakara, 153)", dua: "Zorlukta sabrı, bollukta şükrü bana nasip ettiğin için hamdolsun." },
        { ayet: "“O, gökleri ve yeri hak ile yaratandır.” (En’am, 73)", dua: "Bu muazzam kainatın bir parçası kıldığın için şükürler olsun." },
        { ayet: "“Allah’ın lütfu çok büyüktür.” (Fetih, 29)", dua: "Büyük lütfunla beni kuşattığın için kalbim şükürle dolu." },
        { ayet: "“O, size işitme, görme ve idrak duyguları verdi.” (Mü’minun, 78)", dua: "Azalarımın selameti ve sağlığım için binlerce kez hamdolsun." },
        { ayet: "“Allah dilediğine hesapsız verir.” (Nur, 38)", dua: "Cömertliğine hayran bir kalp ile sana şükrediyorum." },
        { ayet: "“Hamd, alemlerin Rabbi olan Allah’adır.” (Fatiha, 2)", dua: "Yaratıcım ve besleyicim olduğun için sana sonsuz şükürler." },
        { ayet: "“Rabbiniz, size geniş merhamet sahibidir.” (An’am, 147)", dua: "Merhametinle muamele ettiğin için hamdolsun." },
        { ayet: "“Allah her şeye kadirdir.” (Bakara, 284)", dua: "Gücünle beni koruduğun için sana minnettarım." },
        { ayet: "“Şüphesiz Allah çok bağışlayandır.” (Hac, 60)", dua: "Ayıplarımı örttüğün ve beni sevdiğin için şükürler olsun." },
        { ayet: "“İyilik edenlere karşılığı ancak iyiliktir.” (Rahman, 60)", dua: "Bana iyilik yapma gücü ve arzusu verdiğin için hamdolsun." },
        { ayet: "“O, sizinle beraberdir.” (Hadid, 4)", dua: "En büyük nimet olan Seninle olma şuurunu bana verdiğin için şükür." },
        { ayet: "“Allah size bir kolaylık diler.” (Bakara, 185)", dua: "Dinimi ve hayatımı kolaylaştırdığın için hamdolsun." },
        { ayet: "“O, duaları hakkıyla işitendir.” (İbrahim, 39)", dua: "Beni duyduğun ve iç sesime cevap verdiğin için şükürler olsun." },
        { ayet: "“Rabbim çok lütufkardır.” (Yusuf, 100)", dua: "Hayatımın her detayındaki lütfun için hamdolsun." },
        { ayet: "“İman edenlerin kalplerini birleştirdi.” (Enfal, 63)", dua: "Beni müslüman kıldığın ve güzel dostlarla tanıştırdığın için şükür." },
        { ayet: "“Oruç tutmanız sizin için daha hayırlıdır.” (Bakara, 184)", dua: "İbadet edebilme sağlığı ve iradesi için hamdolsun." },
        { ayet: "“Sonuç hayırlı olanlarındır.” (Kasas, 83)", dua: "Beni de o hayırlı sona ulaştıracak kullarından eyle ya Rabbi." }
    ]
};
