import { StyleSheet } from 'react-native';
import { ISLAMI_RENKLER } from '../../constants/renkler';
import { TYPOGRAPHY } from '../../constants/typography';

export const ekstraStiller = StyleSheet.create({
  bolum: {
    backgroundColor: ISLAMI_RENKLER.arkaPlanYesilOrta,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  bolumHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  bolumBaslik: {
    fontSize: 20,
    fontWeight: 'bold',
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontFamily: TYPOGRAPHY.display,
    letterSpacing: 0.2,
  },
  ekleButonu: {
    backgroundColor: ISLAMI_RENKLER.altinOrta,
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ekleButonuText: {
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: TYPOGRAPHY.display,
  },
  yenileButonu: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  yenileButonuText: {
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontSize: 13,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.body,
  },
  istatistikKart: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
  },
  istatistikDeger: {
    fontSize: 36,
    fontWeight: 'bold',
    color: ISLAMI_RENKLER.altinAcik,
    marginBottom: 8,
    fontFamily: TYPOGRAPHY.display,
    letterSpacing: 0.6,
  },
  istatistikLabel: {
    fontSize: 14,
    color: ISLAMI_RENKLER.yaziBeyazYumusak,
    fontFamily: TYPOGRAPHY.body,
  },
  listeContainer: {
    marginTop: 16,
    gap: 8,
  },
  listeItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    padding: 12,
  },
  listeItemBaslik: {
    fontSize: 16,
    fontWeight: 'bold',
    color: ISLAMI_RENKLER.yaziBeyaz,
    marginBottom: 4,
    fontFamily: TYPOGRAPHY.display,
  },
  listeItemTarih: {
    fontSize: 12,
    color: ISLAMI_RENKLER.yaziBeyazYumusak,
    fontFamily: TYPOGRAPHY.body,
  },
  listeItemAciklama: {
    fontSize: 14,
    color: ISLAMI_RENKLER.yaziBeyaz,
    marginTop: 4,
    fontFamily: TYPOGRAPHY.body,
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  switchLabel: {
    fontSize: 16,
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontFamily: TYPOGRAPHY.body,
  },
  aralikContainer: {
    marginTop: 16,
  },
  bilgiText: {
    fontSize: 14,
    color: ISLAMI_RENKLER.yaziBeyazYumusak,
    marginTop: 12,
    fontStyle: 'italic',
    fontFamily: TYPOGRAPHY.body,
  },
  menuListContainer: {
    marginTop: 12,
    gap: 8,
  },
  menuItem: {
    padding: 8,
  },
  menuItemText: {
    fontSize: 15,
    color: ISLAMI_RENKLER.yaziBeyaz,
    lineHeight: 24,
    fontFamily: TYPOGRAPHY.body,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: ISLAMI_RENKLER.arkaPlanYesilOrta,
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  modalBaslik: {
    fontSize: 22,
    fontWeight: 'bold',
    color: ISLAMI_RENKLER.yaziBeyaz,
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: TYPOGRAPHY.display,
    letterSpacing: 0.3,
  },
  modalAciklama: {
    fontSize: 16,
    color: ISLAMI_RENKLER.yaziBeyaz,
    marginBottom: 24,
    textAlign: 'center',
    fontFamily: TYPOGRAPHY.body,
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
    padding: 14,
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontSize: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    fontFamily: TYPOGRAPHY.body,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  modalButonlar: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  modalButonu: {
    flex: 1,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  iptalButonu: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  kaydetButonu: {
    backgroundColor: ISLAMI_RENKLER.altinOrta,
  },
  modalButonuText: {
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontWeight: 'bold',
    fontSize: 16,
    fontFamily: TYPOGRAPHY.body,
  },
  hesaplaButonu: {
    backgroundColor: ISLAMI_RENKLER.altinOrta,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    marginTop: 12,
  },
  hesaplaButonuText: {
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontWeight: 'bold',
    fontSize: 16,
    fontFamily: TYPOGRAPHY.body,
  },
  sonucKart: {
    marginTop: 16,
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: ISLAMI_RENKLER.altinAcik,
  },
  sonucLabel: {
    fontSize: 14,
    color: ISLAMI_RENKLER.yaziBeyazYumusak,
    marginBottom: 8,
    fontFamily: TYPOGRAPHY.body,
  },
  sonucDeger: {
    fontSize: 28,
    fontWeight: 'bold',
    color: ISLAMI_RENKLER.altinAcik,
    marginBottom: 4,
    fontFamily: TYPOGRAPHY.display,
    letterSpacing: 0.4,
  },
  sonucAciklama: {
    fontSize: 12,
    color: ISLAMI_RENKLER.yaziBeyazYumusak,
    fontStyle: 'italic',
    fontFamily: TYPOGRAPHY.body,
  },
  kaloriItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  kaloriInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 10,
    padding: 12,
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontSize: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    fontFamily: TYPOGRAPHY.body,
  },
  silButonu: {
    backgroundColor: 'rgba(198, 40, 40, 0.3)',
    borderRadius: 20,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  silButonuText: {
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: TYPOGRAPHY.display,
  },
  toplamKaloriKart: {
    marginTop: 16,
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: ISLAMI_RENKLER.yesilParlak,
  },
  toplamKaloriLabel: {
    fontSize: 16,
    color: ISLAMI_RENKLER.yaziBeyaz,
    fontWeight: '600',
    fontFamily: TYPOGRAPHY.body,
  },
  toplamKaloriDeger: {
    fontSize: 24,
    fontWeight: 'bold',
    color: ISLAMI_RENKLER.yesilParlak,
    fontFamily: TYPOGRAPHY.display,
  },
});
